trigger:
-main 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Docker image builder'
  inputs:
    command: build
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
        latest 